project:
  type: website
  render:
    - "*.md"
    - "*.qmd"

website:
  favicon: ./assets/images/favicon.svg
  repo-url: https://github.com/KalroDevs/lschub-cms
  repo-actions:
    - edit
    - issue
  page-footer:
    left:
    - text: LSC Hubs 2024
      file: https://www.lsc-hubs.org
  title: "Land Soil Crop Hub {{< var country >}}"
  search: false
  navbar:
    pinned: true
    logo: ./assets/images/logo.svg
    logo-alt: "Logo of Land Soil Crop Hub {{< var country >}}"
    right:
      - text: Data and Information
        file: "/#data-and-information"
      - text: Maps
        file: "/#maps"
      - text: User stories
        file: "/#user-stories"
      - text: Community
        file: "/#hub-community"
      - text: Docs
        file: "/#documents"
  sidebar:
    - title: "Docs"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - text: User
          file: docs/user
        - text: Administrator
          file: docs/admin
        - section: Developer
          contents:
            - section: Hub components
              contents: docs/developer/*
            - section: Workshop Data
              contents: docs/developer/tutorial-data-management/*

format:
  html:
    page-layout: full
    theme:
      - ./assets/css/custom.scss
    code-copy: true
    code-overflow: wrap
    filters:
      - ./filters/page-section/_extensions/page-section/page-section.lua
    shortcodes:
      - ./shortcodes/icon-link/_extensions/icon-link/icon-link.lua
