---
title: "1.3 Tools"
subtitle: "A suggestion for relevant tools in data management"
author: Paul van Genuchten
date: 2023-05-09
format:
  revealjs:
    incremental: true
    logo: https://lsc-hubs.org/images/logo-lsc-hubs.svg
    footer: "Workshop on effective spatial data management"
---

## Github

Service to facilitate co-creation

- version history of contributions
- authentication
- issue management
- release management
- Continuous integration

Related software; Git, Gitlab, Bitbucket, Codeberg

## Quarto

A content management system to create websites, documentation, slides, etc.

Related software; [Hugo](gohugo.io), [mkdocs](https://mkdocs.org), Jekyll, [Wordpress](https://wordpress.org), [Drupal](https://drupal.org)

## pygeometa / geodatacrawler

Scripting libraries which support data management of a file repository

- Generate metadata from existing data
- Import remote metadata
- Ingest metadata from a file repository
- Create mapservices (APIs) for existing data

## pycsw

A catalogue server application providing support for multiple metadata schemes and metadata exchange standards

Related products; GeoNetwork, CKAN, Dataverse

## Mapserver

A server application providing OGC services (WMS, WFS, WCS) on various data formats

Related products; Geoserver, ArcGIS server, deegree, pygeoapi, QGIS server

## TerriaJS

A WebGIS application including Leaflet library

[demo](https://maps.lsc-hubs.org/#rwanda)

Related products; GeoNode, GeoMoose, MapBender, Oskari, [GisQuick](https://gisquick.org/)



